MEGA65/mega65-user-guide

- userguide.tex
* Removed twoside from book, as this is the default and not required for book
* Change left and right margining to inner and outer. Also removed any margin text support
* Introduced sloppy to improve wrap calculations mainly for section headings
* Added raggedright for the sections so that they do not justify.
> Correct headings and book formatting

- elements/keys.tex
This corrects the vertical centre for the
keys with the surrounding text.
#22
> Correct baseline for megakey macro.

- appendix-basic10.tex
- basic-fragments.tex
- element-catalogue.tex
- elements/screenoutput.tex
- gettingstarted.tex
- howcomputerswork.tex
- introduction.tex
- mega65-book.tex
- settingup.tex
- userguide.tex
BASIC 10 text changes
Some typo corrections
Moved common blocks from the BASIC text into a fragments file.
Not all suggestions were implemented, for example: formatting styles, internationalisation, some suggestions and so forth.
How ironic that this review was way better than my own command of the English language.
Mind you, not to suggest that Australian English can really be classed as English.
Certainly not to the standard that Her Majesty would expect.
>  Text revision changes from cheveroninuk's review

- appendix-asciicodes.tex
A few CHR$ codes were missing in the table. This PR adds them and switches to a multicols layout for better maintainability of the table in the latex sources.
> Add missing CHR$ codes, use \screentext and use multicols for table

- appendix-mega65r2-flashing.tex
- hardwareguide.tex
- nexys4ddr-setup.tex
1. Changed title wording away from Artix T100 FPGA as there was confusion around the use of extra hardware required for bitstream flashing on the MEGA65 R2/R2 but not the Nexyx FPGA Dev Board
2. Added hardware chapters to the hardware guide to fix broken label/refs used.
3. Sentence revision in appendix-mega65r2-flashing.tex
Requires a PR as the FPGA changes were done blind and need double checking.
> FPGA clarifications and revisions

- appendix-basic10.tex
A few additions to the BASIC10 chapter with some commands (and extensions to existing commands) that work on the 0.9B.911001 ROM:
RWINDOW (previously undocumented)
PIXEL (previously undocumented; the documented equivalent RDOT doesn't work on the 911001 ROM)
LINE (additional functionality)
LIST (additional functionality)
CHAR (additional functionality)
> Basic10 additions

- assemblers.tex
This is an update to the assembler page where I tried to simplify and make the writing style slightly more towards what I would expect in a manual /  book. Things to check:
I have unfortunately been unable to compile as I cannot create a working LaTeX setup. This is due to the dependency on `mega65-tools` which does not compile on macOS (due to hardcoded Makefiles) and not on my linux either (due to errors with windows cross compilation; can this be disabled?). I suspect these issues could present some barrier for contributing and I have thought of re-writing the build-system to `CMake` (of `mega65-tools`). Before going in that direction, I would like to hear if this has any interest? (ping @gardners).
> Update assembler section

- appendix-basic10-condensed.tex
BSAVE syntax was slightly off. The "P" is needed before each part of the address.
> corrects BSAVE syntax

- transferanddebugging.tex
Adds documentation for m65 unit test support and C and BASIC65 support routines.
Also, a working example in BASIC65 is provided.
> Unit test support documentation

- appendix-basic65.tex
I removed the `=` characters when describing function parameters to be more inline with the c64 use manual and proof read from ~2500 - 3200.
Sorry for the mish-mash of fixes. I'll try not to mix them in future.
> Basic65 prood read part iv

- appendix-basic65.tex
This small change reuses a dir listing in the CATALOG command. Now the DIR command refers to it instead of duplicating it, saving just over half a page.
> reuse wide parameter dir listing

- appendix-basic65.tex
- appendix-donors.tex
- appendix-instructionset.tex
- style-guide.md
Didn't really fix a lot of wording here. This PR is to standardise the use of `keyword` and `command`. I removed most of them, since the keywords/tokens are already in bold, the fact that it's a keyword is implied. Not only that, but the fact that they're in bold is documented at the start of the page.
> Basic65 proof read part ix

- appendix-45gs02-registers.tex
- appendix-45io27-registers.tex
- appendix-basic65.tex
- appendix-decbinhex-tutorial.tex
- appendix-keyboard.tex
- appendix-monitor.tex
- appendix-petsciicodes.tex
- appendix-viciv-registers.tex
- beginninginbasic.tex
- common-header.tex
- configuring.tex
- cores-and-flashing.tex
- developing-system-programs.tex
- freezer.tex
- gettingstarted.tex
- introduction.tex
- modes.tex
- nexys4ddr-setup.tex
- screen-editor.tex
- settingup.tex
- style-guide.md
- transferanddebugging.tex
Starting my 2nd pass of the user's guide. Went over Chapters 1-3. After having done a pass of the book im much more familiar with it so was able to make some changes to keep everything more consistent with capitalisation of various menus.
The main thing done in this PR was the use of keys. I made sure the tags were used, and instead of pointing out keys with `the <blah> key`, the wording is simply `<blah>`. Some parts used the former, others the latter.
I think the latter (`<blah>`) looks better so changed it all to keep the guide consistent.
> Proof Read Second Pass Chapters 1-3

- appendix-petsciicodes.tex
As discussed in discord.
Changes NOTE: to Note: for consistency with the rest of the document.
Also Changed NOTE2: to Notes: 
I opted to not start a new line with 1. so it didn't shift the following pages out of whack. (I tested locally first)
> NOTE: to Note: for consistency. And NOTE2: changed

- appendix-45gs02-registers.tex
I noticed the description of ASRQ is a duplicate of ASLQ (directly above). I'm not aversed in the Latex format, but I think I found the cause for the missing matching data. 
There still needs to be a inst.ASRQ file!
> Fix description of ASRQ?

- appendix-basic65.tex
Particularly that it doesn't map the first block and addresses $0000-$1FFF is the RAM in bank 0 regardless of **BANK**.
I resisted the temptation to explain why **SYS** works this way. But I'm happy to give in to it if it's felt such an explanation would be warranted.
> Add a remark on how SYS maps memory when it's combined with BANK.

- appendix-instructionset.tex
- instruction_set.c
This is just the table of contents that appears in the PDF viewer, not the table of contents LaTeX produces on the actual pages.
This is makes it easier to locate and jump between the instructions, without having to go via the index pages.
> Add the individual asm instructions to the PDF table of contents.

- appendix-instructionset.tex
the example was: JMP ($1234) but should have been JMP ($1234,X)
> Fixed Absolute Indirect X-Indexed Mode example

- appendix-45gs02-registers.tex
Fixed typo for 32-bit address example where the text was '43' instead of '34'
> Fixed type on 32-bit address example

- .gitignore
- Makefile
- README.md
- appendix-petsciicodes.tex
This adds the ESC Home feature introduced in ROM 920362 to the Escape Sequences section of the User Guide appendix.
This also adds keymap as a recognized generated asset, so a clean build now succeeds.
I added notes to the set-up instructions in the README about where the dependent repos go (in the parent directory). My editor decided to normalize some Markdown formatting; sorry about that. :)
> Add mention of new ESC Home feature (ROM 920362); gitignore & README cleanup

- appendix-viciv-registers.tex
This rewrites description of VIC-IV "hot" registers for clarity, based on recent Discord discussion. See issue #477.
> Rewrote description of VIC-IV "hot" registers

- ccompilers.tex
This mentions lthe lvm-mos compiler to the "C and C-like compilers" section for C99, C++, and Rust development.
> Add LLVM mos compiler

- appendix-viciv-registers.tex
This fix makes the following chapter (Relocating Color/Attribute RAM) render correctly again.
> Fix screenoutput block in VIC-IV registers

- appendix-instructionset.tex
Six addressing modes are documented as currently having no instructions that support them. This PR disables the mention of these modes, but retains the text in the source file for later.
Disabled:
- Base-Page Quad Y-Indexed Mode
- Base-Page Z-Indexed Mode
- Base-Page Quad Z-Indexed Mode
- Absolute Quad Y-Indexed Mode
- Base-Page Quad Indirect X-Indexed Mode
- Base-Page Quad Indirect Y-Indexed Mode
Related modes that are not documented as having no instructions are still enabled:
- Base-Page X-Indexed Mode
- Base-Page Y-Indexed Mode  (removes Z)
- Base-Page Quad X-Indexed Mode  (removes Y, Z)
- Absolute Quad X-Indexed Mode  (removes Y)
- Base-Page Quad Indirect Z-Indexed Mode  (removes X, Y)
> Disable addressing modes documented as having no instructions

- appendix-45gs02-registers.tex
The section mentioned describes usage of register $d7fa to fine-tune the CPU speed (SPEEDBIAS). This register is no longer available, and is used for FRAMECOUNT instead. Thus, we should remove the outdated section.
> Removed deprecated section "CPU Speed Fine-Tuning"

- appendix-viciv-registers.tex
- assemblers.tex
Adding a section about character alpha-blending. We still need to add something about sprite alpha-blending, but this can be part of a future PR.
> Adding alpha-blending description for characters

- .gitignore
- appendix-basic65.tex
- appendix-decbinhex-tutorial.tex
- appendix-instructionset.tex
- appendix-monitor.tex
- mega65-book.tex
- memory.tex
- referenceguide.tex
This is a tutorial-style introduction to MEGA65 memory topics with a focus on programming in "MEGA65 mode." It is not meant to comprehensively describe every feature of the memory-related hardware, and defers to appendices for rigor.
PDF of the draft chapter for review convenience:
[DRAFT-memory.pdf](https://github.com/MEGA65/mega65-user-guide/files/10533993/DRAFT-memory.pdf)
I'm interested in review from novices for clarity, and from experts for accuracy. Please point out typos, code sample errors, and typesetting issues. Feel free to leave feedback as comments on the PR if you don't want to go hunting through the memory.tex file for lines of source, though line comments are also fine. If you'd rather provide feedback privately, you can DM me on Discord (dddaaannn#7325).
Portions of this …
> New chapter: Memory

- appendix-basic65.tex
- appendix-petsciicodes.tex
ROM 920382 adds an 80x50 (ESC+5) text mode to the BASIC 65 environment, complementing the 80x25 (ESC+8) and 40x25 (ESC+4) text modes. The `T@&` and `C@&` have corresponding larger ranges in this mode. https://github.com/MEGA65/mega65-rom/pull/13
I also removed one mention of POKE'ing screen memory, because the location is not the same in all text modes. BASIC programs should usually use `T@&` and `C@&` to access screen and color memory, or they can read VIC-IV registers to locate screen memory.
> Document 80x50 mode, new in ROM 920382

- appendix-memorymap.tex
A couple little things I noticed while reading this section again.
Wasn't sure if the first should be "in the MEGA65" or "on the MEGA65".  They both sounds ok to me, so probably just a style thing.  Searching shows many instances of both ways.
The second one could also be "from within" if that's preferred.
> Minor English fixes in memory map appendix

- appendix-instructionset.tex
The escaped $ was causing the output to have an extra British pound symbol in the example.
> Remove escape from screenoutput block

- appendix-monitor.tex
The escaped `@` symbol (`\@`) means something special in TeX so it wasn't being rendered as an `@`.  Plus there was a small copy and paste error in the in-line example
> Fix a couple matrix monitor typos

- appendix-monitor.tex
- '@' Add comma to usage when specifying command
- '@' Add directory ($) info
- 'A' 1-3 byte long machine code (should be 5)
- 'A' Fix Remarks: supports Q now
- 'D' Add note about NEG NEG rendering as '*'
- '@', 'V', 'L' & 'S' unit radii note
> Monitor Appendix: Reflect recent ROM changes

- appendix-basic65.tex
`XC=XC+WT*320:YC=YC+HT*200` does nothing because `WT` and `HT` are never set and are thus zero -- making XC=XC and YC=YC.
The history shows that this was left over from a previous revision (which also wasn't right because the variables were named `H` and `W`)
> Remove useless line from CIRCLE example

- appendix-keyboard.tex
The C65 introduced a ninth keyboard matrix column. As the well-known scanning via CIA1 is now not enough anymore, users need to understand how to control all nine columns now. This information is still lacking in the documentation, which this PR is now addressing.
> Adding information how to control keyboard matrix column 8

- mega65-book.tex
- mega65-chipset-reference.tex
I overlooked the fact that the new section for the RTC clock needed to be added to the mega65-*.tex as well. It was previously only added to the referenceguide.tex (see 7f882964ce) which is not published. 
I would be happy if the new sections would be added to the book and chipset reference as well, if it is considered as useful.
Thanks! :)
> Added missing includes into mega65-book and mega65-chipset-reference

- instruction_sets/inst.CMPQ
- instruction_sets/inst.ROLQ
- instruction_sets/inst.RORQ
- instruction_sets/inst.SBCQ
Noticed a few minor issues with some of the Q opcodes: 
- The SBCQ, CMPQ opcode during operation referenced A-M instead of Q-M. 
-  The RORQ and ROLQ opcodes on the symbolic operation, did not reflect the Q case.
> Minor tweaks for for Q opcodes
