MEGA65/mega65-user-guide

elements/spritegrid.tex
userguide.tex

Supports both mono hi-res and multi-coloured sprites.

24 x 21 sprite grid element.

---

README.md

now that there are more requirements to build.

First flesh out of the README.md

---

document-memory.c

Fixed bzero error for mingw32 systems.

---

appendix-decbinhex-tutorial.tex
appendix-reference-tables.tex
userguide.tex

Hi
Please review.
Thanks,
Mark

Added files for decimal, binary, hex tutorial and reference tables

---

element-catalogue.tex
elements/graphicsymbol.tex
elements/keys.tex
userguide.tex

Graphic Key and Mega macros

---

appendix-keyboard.tex

The new chapter about the MEGA65 Keyboard is great. This PR provides small fixes/improvements.

Small fixes for appendix-keyboard.tex

---

Makefile
get-fonts

(Fixes all book builds for MinGW users)

 Removed get-fonts / GCC as default compiler

---

configuring.tex

A few minor things I stumpled upon while gleefully reading the manual
Specifically:
- removed informal "doesn't"
- removed redundant "definitely"
- removed exclamation sign; it hurt my eyes
- avoid negation
- prefer active over passive form

Slightly tighter language

---

appendix-mega65r2-flashing.tex
cores-and-flashing.tex

I've tried to keep the language consistent throughtout, including refering to blue flashing "lights" everywhere (instead of "LEDs" previously used in the appendices).
Fixes #110

Updates for ambulance mode

---

introduction.tex

My recommended narrative changes to the introduction. Let me know if my writing style matches your intent.

Modification to Introduction

---

settingup.tex

If you guys are OK with the changes I made here, I'm more than happy to continue with the rest of the manual.

Went over the setting up tex file and cleaned it up.

---

appendix-troubleshooting.tex

Guide to rectify missing dependency ncurses for building target mega65_ftp

Add guide to troubleshooting -lncurses error

---

gettingstarted.tex

I made a few minor tweaks to the wording and grammar. Merge/Reject as you see fit!

Getting started grammar

---

configuring.tex

This file is relatively large and might need splitting up. I have gone over it and proof read it, and made some changes. As usual - please comment and reject if i've taken it too far

Configuring proof read

---

modes.tex

I have gone over it and proof read it, and made some changes. As usual - please comment and reject if I've taken it too far

Modes proof read

---

cores-and-flashing.tex

Been a while between PRs from me, i went over the next section in the manual. 
I will be creating a style guide when i have time

cores and flashing proof read

---

cores-and-flashing.tex

Sorry guys, while making changes last week for the style guide I reverted this to a previous version that was prior to my proof read. This fixes that.

Cores and flashing fixes (again)

---

appendix-basic65.tex
appendix-keyboard.tex
beginninginbasic.tex
configuring.tex
gettingstarted.tex
introduction.tex
screen-editor.tex
settingup.tex

After seeing my error on the cores page i thought I'd quickly go over the parts before the basic appendix again to sanity check it.
You can see from my changes i replaced coder with programmer, and used hyphens to keep the English a bit tighter.

went over the start of the manual and tidied it up a little

---

appendix-45io27-registers.tex
appendix-basic65.tex
appendix-dmagic.tex
appendix-instructionset.tex

more standardisation, updated style guide and appendix proof read lines 5500-6500

Basic65 proof read part viii

---

appendix-45gs02-registers.tex
appendix-basic65.tex
appendix-keyboard.tex
appendix-petsciicodes.tex
beginninginbasic.tex
configuring.tex
cores-and-flashing.tex
element-catalogue.tex
elements/keys.tex
gettingstarted.tex
nexys4ddr-setup.tex
screen-editor.tex
style-guide.md

also standardised the use of more keys in the manual and added a few pagerefs

petscii appendix proof read

---

screen-editor.tex

fixed spelling mistake. vom to from.

Update screen-editor.tex - fixed spelling mistake. vom to from. 

---

appendix-basic65.tex

Basic65 basic proof read xi

---

screen-editor.tex

Megakey-4 is dark gray, not green.

---

appendix-basic65.tex
configuring.tex
screen-editor.tex

last section of the basic65 proof read

Basic65 basic proof read xii

---

appendix-basic65.tex

Did my last PR again this time with @Edilbert 's latest changes.

basic65 touch up

---

appendix-45gs02-registers.tex
appendix-decbinhex-tutorial.tex
appendix-dmagic.tex
appendix-reference-tables.tex
appendix-viciv-registers.tex
style-guide.md

Closes#312
Added consistent spelling for half byte mentions. Thanks @johnwayner

#312 Use consistent spelling for half byte

---

cores-and-flashing.tex
modes.tex
style-guide.md

3 grammatical typos and code example typo.

Patch 1 - Core, Screen and style guide - 4 typos including code example

---

appendix-45gs02-registers.tex
appendix-45io27-registers.tex
appendix-dmagic.tex
appendix-hypervisor-calls.tex
appendix-memorymap.tex
appendix-troubleshooting.tex
configuring.tex
cores-and-flashing.tex
modes.tex
settingup.tex
style-guide.md

* Also standardised use of (tm), added a registered trademark for the first mention of Vivado.
* Standard case of SD card mentions.
* Removed some flashing text specific to dev/nexys devices which will only show in the book.

Chapter 6 proof read second pass

---

appendix-basic65.tex
basic-fragments.tex
freezer.tex
modes.tex
screen-editor.tex
settingup.tex

This PR's aim is to fix a bunch of small issues, that don't need to have their own PR. Please dont merge this until it gets big enough, or the deadline has been reached.
Edit: I think it's big enough now

fix various small issues

---

appendix-donors.tex

I hope these names aren't updated from outside this code and that this sort of PR is okay.

Fix my name in donors section.

---

appendix-basic65.tex
freezer.tex
settingup.tex

Closes #433 . At least i _think_ it does. @MauriceMEGA65 you might want to double check as well

fix for #433

---

appendix-45e100-registers.tex
appendix-monitor.tex
developing-system-programs.tex

Fixes Issue https://github.com/MEGA65/mega65-user-guide/issues/451
and other unreported issues.

Fix various simple typos.

---

appendix-dmagic.tex

Fixed typo where into was written inti

---

appendix-donors.tex

It turns out my name was spelled wrong, but I'd prefer if my *full* name wasn't here at all

Remove name

---

appendix-dmagic.tex

Next sample value, not next sample

---

appendix-45gs02-registers.tex

Alt + tab does not trigger debug interface. Also, fixed a couple words.

Debug interface is triggered with mega key + tab

---

appendix-basic65.tex

This command is no longer supported since ROM version 338

Remove "COLOR ON" and "COLOR OFF" usage

---

appendix-instructionset.tex
appendix-memorymap.tex
instruction_sets/inst.TSX

Fixing some mistakes in the instruction set descriptions

Instruction set corrections

---

appendix-basic65.tex

Too much explanation, at this point in the text.

Commented out some text. 

---

appendix-viciv-registers.tex
instruction_sets/inst.DEW
instruction_sets/inst.INW

I edited these directly on Github and its editor decided to put a new line (I think) at the end of the INW and DEW files.  If you think that will be a problem, feel free to edit them out or reject the PR.

A few more simple fixes

---

appendix-45io27-registers.tex

Hopefully these many small fix PRs aren't annoying...  But if I wait for lots of changes to build up, I'll forget about them.

Fix the smallest of typos

---

howcomputerswork.tex

I'm currently using xemu, have pre-ordered the MEGA65 hardware. I'm going through the user guide for the first time and found a few obvious grammar related errors. If I can contribute even a little bit by proofreading, I'm glad to be a part.
Please be gentle if I mess up any git best practices, and correct me. I'm still new to this!

Mega65 user guide grammar

---

appendix-4541-hw-iec.tex

The new commands are pending this PR: https://github.com/MEGA65/mega65-core/pull/825

Appendix 4541: Fix $52/$72; Describe new: $4C,$50,$70

---

appendix-rtc-registers.tex
appendix-special-registers.tex
referenceguide.tex

This is work in progress.
I've added the missing documentation of the RTC-Chip. It was not shown at all ...

Add missing documentation of the RTC
